# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: question_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d question_bank"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/question_bank

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Apply migrations
        run: deno task db:apply

      - name: Generate Prisma client
        run: deno task db:generate

      - name: Seed database
        run: deno task db:seed

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task tests
